### PR TITLE
Small note regarding multi-core support

### PR DESCRIPTION
**Pull request by KetothXupack**
I think that OpenMP threading support it is worth mention for CPU-guys :)

### CODE REVIEW

**Comment by awentzonline** [comment]
Thank you!

**Comment by KetothXupack** [comment]
np! :open_hands:

**Comment by alexjc** [comment]
Do you get any benefits from OpenMP on your machine? I tried two different CPUs and saw minor improvements and often regressions by 1-2% or more.

**Comment by awentzonline** [comment]
I just checked to see that it worked and didn't profile anything; it still seemed really slow.

Rather than find the right thing to make Theano happy, I'm focusing on making this compatible with the keras TensorFlow backend which is way more performant and straightforward to use on CPU (in my experience, anyways).

**Comment by KetothXupack** [comment]
I made it run ~4-5x faster on 32x-core Xeon for one particular transformation. Also I really not sure if I picked correct tensor size threshold. Too low value really leads to performance degrade.

**Pull request merged**
